-- Period cycles (start/end dates) per user — replaces local-only period storage when remote is used.
CREATE TABLE IF NOT EXISTS public.period_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  CONSTRAINT period_records_start_end_chk CHECK (end_date IS NULL OR end_date >= start_date),
  CONSTRAINT period_records_user_start_uniq UNIQUE (user_id, start_date)
);

ALTER TABLE public.period_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own period_records"
  ON public.period_records
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE TRIGGER on_period_records_updated
  BEFORE UPDATE ON public.period_records
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS period_records_user_start_idx
  ON public.period_records (user_id, start_date DESC);

-- Diary notes (per calendar day, multiple entries per day allowed)
CREATE TABLE IF NOT EXISTS public.diary_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entry_date DATE NOT NULL,
  body TEXT NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  CONSTRAINT diary_entries_body_len_chk CHECK (char_length(body) <= 2000)
);

ALTER TABLE public.diary_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own diary_entries"
  ON public.diary_entries
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE TRIGGER on_diary_entries_updated
  BEFORE UPDATE ON public.diary_entries
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS diary_entries_user_date_idx
  ON public.diary_entries (user_id, entry_date DESC, recorded_at DESC);
