-- Create schedules table
CREATE TABLE IF NOT EXISTS public.schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT,
  has_rec BOOLEAN DEFAULT false,
  old_time TEXT,
  rec_time TEXT,
  rec_desc TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

-- Allow users to manage (CRUD) only their own schedules
CREATE POLICY "Users can manage their own schedules" 
ON public.schedules 
FOR ALL 
USING ( auth.uid() = user_id )
WITH CHECK ( auth.uid() = user_id );

-- profiles 마이그레이션이 일부만 적용된 원격 DB에서도 동작하도록, 트리거용 함수를 여기서 한 번 더 정의합니다.
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach updated_at trigger (function was created in the profiles migration)
CREATE TRIGGER on_schedules_updated
  BEFORE UPDATE ON public.schedules
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();
